//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Animal</summary>
	[PublishedContentModel("animal")]
	public partial class Animal : PublishedContentModel, IBanner
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "animal";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Animal(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Animal, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Animal Description: Enter a thorough description of the animal
		///</summary>
		[ImplementPropertyType("animalDescription")]
		public IHtmlString AnimalDescription
		{
			get { return this.GetPropertyValue<IHtmlString>("animalDescription"); }
		}

		///<summary>
		/// Animal height: Enter the height of the animal
		///</summary>
		[ImplementPropertyType("animalHeight")]
		public string AnimalHeight
		{
			get { return this.GetPropertyValue<string>("animalHeight"); }
		}

		///<summary>
		/// Animal Name: Enter the name of the animal in this field
		///</summary>
		[ImplementPropertyType("animalName")]
		public string AnimalName
		{
			get { return this.GetPropertyValue<string>("animalName"); }
		}

		///<summary>
		/// Animal weight: enter the weight of the animal
		///</summary>
		[ImplementPropertyType("animalWeight")]
		public string AnimalWeight
		{
			get { return this.GetPropertyValue<string>("animalWeight"); }
		}

		///<summary>
		/// Gallery image-1: Upload the first image for the gallery
		///</summary>
		[ImplementPropertyType("galleryImage1")]
		public IPublishedContent GalleryImage1
		{
			get { return this.GetPropertyValue<IPublishedContent>("galleryImage1"); }
		}

		///<summary>
		/// Gallery image-2: Upload the second image for the gallery
		///</summary>
		[ImplementPropertyType("galleryImage2")]
		public IPublishedContent GalleryImage2
		{
			get { return this.GetPropertyValue<IPublishedContent>("galleryImage2"); }
		}

		///<summary>
		/// Gallery image-3: Upload the third image for the gallery
		///</summary>
		[ImplementPropertyType("galleryImage3")]
		public IPublishedContent GalleryImage3
		{
			get { return this.GetPropertyValue<IPublishedContent>("galleryImage3"); }
		}

		///<summary>
		/// Image animal: Select a picture to be shown on the animal cards
		///</summary>
		[ImplementPropertyType("imageAnimal")]
		public IPublishedContent ImageAnimal
		{
			get { return this.GetPropertyValue<IPublishedContent>("imageAnimal"); }
		}

		///<summary>
		/// Short description: A short description to be shown on the animals page
		///</summary>
		[ImplementPropertyType("shortDescription")]
		public string ShortDescription
		{
			get { return this.GetPropertyValue<string>("shortDescription"); }
		}

		///<summary>
		/// Animal Banner: Select an image to be shown on the animal cards on the animals list
		///</summary>
		[ImplementPropertyType("bannerImage")]
		public IPublishedContent BannerImage
		{
			get { return Umbraco.Web.PublishedContentModels.Banner.GetBannerImage(this); }
		}
	}
}
